"""create_core_numm_tables

Revision ID: 919a8444baa6
Revises: 
Create Date: 2026-09-23 11:16:41.415325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919a8444baa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('common_material_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnmc_code', sa.String(length=100), nullable=False),
    sa.Column('standardized_description', sa.Text(), nullable=False),
    sa.Column('standardized_specification', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('uom_standard', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('common_material_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_common_material_codes_cnmc_code'), ['cnmc_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_common_material_codes_id'), ['id'], unique=False)

    op.create_table('cpses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sap_system_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cpses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cpses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_cpses_id'), ['id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpse_id', sa.Integer(), nullable=False),
    sa.Column('cpse_material_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('specification_text', sa.Text(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('classification_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cpse_id'], ['cpses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_cpse_code', ['cpse_id', 'cpse_material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_cpse_id'), ['cpse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_cpse_material_code'), ['cpse_material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_description'), ['description'], unique=False)
        batch_op.create_index('ix_materials_description_trgm', ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('cpse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cpse_id'], ['cpses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_cpse_id'), ['cpse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('candidate_material_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_candidates_candidate_material_id'), ['candidate_material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_material_id'), ['material_id'], unique=False)

    op.create_table('material_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cnmc_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cnmc_id'], ['common_material_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_mappings_cnmc_id'), ['cnmc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_mappings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_mappings_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_mappings_material_id'))
        batch_op.drop_index(batch_op.f('ix_material_mappings_id'))
        batch_op.drop_index(batch_op.f('ix_material_mappings_cnmc_id'))

    op.drop_table('material_mappings')
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_candidates_material_id'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_id'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_candidate_material_id'))

    op.drop_table('match_candidates')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_cpse_id'))

    op.drop_table('users')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_id'))
        batch_op.drop_index('ix_materials_description_trgm')
        batch_op.drop_index(batch_op.f('ix_materials_description'))
        batch_op.drop_index(batch_op.f('ix_materials_cpse_material_code'))
        batch_op.drop_index(batch_op.f('ix_materials_cpse_id'))
        batch_op.drop_index('ix_materials_cpse_code')

    op.drop_table('materials')
    with op.batch_alter_table('cpses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cpses_id'))
        batch_op.drop_index(batch_op.f('ix_cpses_code'))

    op.drop_table('cpses')
    with op.batch_alter_table('common_material_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_common_material_codes_id'))
        batch_op.drop_index(batch_op.f('ix_common_material_codes_cnmc_code'))

    op.drop_table('common_material_codes')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
